'use server';
/**
 * @fileOverview Generates an initial data structure (fields, categories, tags) based on a user-provided prompt describing the type of personal information they want to organize.
 *
 * - generateInitialStructure - A function that generates the initial data structure.
 * - GenerateInitialStructureInput - The input type for the generateInitialStructure function.
 * - GenerateInitialStructureOutput - The return type for the generateInitialStructure function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const GenerateInitialStructureInputSchema = z.object({
  prompt: z
    .string()
    .describe(
      'A prompt describing the type of personal information the user wants to organize (e.g., travel plans, project notes, recipes).'
    ),
});
export type GenerateInitialStructureInput = z.infer<
  typeof GenerateInitialStructureInputSchema
>;

const GenerateInitialStructureOutputSchema = z.object({
  dataStructure: z
    .string()
    .describe(
      'A JSON string representing the initial data structure (fields, categories, tags) generated by the AI, ready for customization.'
    ),
});
export type GenerateInitialStructureOutput = z.infer<
  typeof GenerateInitialStructureOutputSchema
>;

export async function generateInitialStructure(
  input: GenerateInitialStructureInput
): Promise<GenerateInitialStructureOutput> {
  return generateInitialStructureFlow(input);
}

const prompt = ai.definePrompt({
  name: 'generateInitialStructurePrompt',
  input: {schema: GenerateInitialStructureInputSchema},
  output: {schema: GenerateInitialStructureOutputSchema},
  prompt: `You are a helpful assistant designed to generate initial data structures based on user prompts.

The user will provide a prompt describing the type of personal information they want to organize. Your task is to generate a JSON string representing a data structure that includes relevant fields, categories, and tags that the user can then customize for their "Smart Personal World".

Ensure that the output is a valid JSON string that can be readily parsed.

User Prompt: {{{prompt}}}`,
});

const generateInitialStructureFlow = ai.defineFlow(
  {
    name: 'generateInitialStructureFlow',
    inputSchema: GenerateInitialStructureInputSchema,
    outputSchema: GenerateInitialStructureOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
